pagina_principal:
    pattern: /
    defaults: { _controller: proyectoHotelBundle:Default:index }

pagina_reservas:
    pattern: /reservar
    defaults: { _controller: proyectoHotelBundle:Reservas:primera }

pagina_reservas_habitacion:
    pattern: /reservar/habitacion
    defaults: { _controller: proyectoHotelBundle:Reservas:habitacion }

pagina_reservas_cliente:
    pattern: /reservar/cliente
    defaults: { _controller: proyectoHotelBundle:Reservas:cliente }

pagina_reservas_finalizar:
    pattern: /reservar/finalizar
    defaults: { _controller: proyectoHotelBundle:Reservas:finalizar }

pagina_reservas_confirmar:
    pattern: /reservar/confirmar/{codigo}
    defaults: { _controller: proyectoHotelBundle:Reservas:confirmar }

contacto:
    path:     /contacto
    defaults: { _controller: proyectoHotelBundle:Contacto:mostrar }
    methods:  [GET]

procesar_contacto:
    path:     /contacto
    defaults: { _controller: proyectoHotelBundle:Contacto:procesar }
    methods:  [POST]

pagina_habitaciones:
    pattern: /habitaciones/{tipo}
    defaults: { _controller: proyectoHotelBundle:Habitaciones:mostrar, tipo: "" }

pagina_hotel:
    pattern: /hotel
    defaults: { _controller: proyectoHotelBundle:Hotel:mostrar }
