pagina_principal:
    pattern: /
    defaults: { _controller: proyectoHotelBundle:Default:index }

pagina_reservas:
    pattern: /reservar
    defaults: { _controller: proyectoHotelBundle:Reservas:primera }

pagina_reservas_habitacion:
    pattern: /reservar/habitacion
    defaults: { _controller: proyectoHotelBundle:Reservas:habitacion }
#    methods:  [POST]

pagina_reservas_cliente:
    pattern: /reservar/cliente
    defaults: { _controller: proyectoHotelBundle:Reservas:cliente }