parameters:
#    proyecto_hotel.example.class: proyecto\HotelBundle\Example

services:
#    proyecto_hotel.example:
#        class: %proyecto_hotel.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    form.type.datePicker:
        class: proyecto\HotelBundle\Form\Type\DatePickerType
        tags:
            - { name: form.type, alias: datePicker }

    purgador:
        class: proyecto\HotelBundle\Controller\PurgaController
        arguments: [ @doctrine.orm.entity_manager ]

    kernel.listener.hotelException:
        class: proyecto\HotelBundle\EventListener\HotelExceptionListener
        arguments:
            - @twig
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }