proyecto\HotelBundle\Entity\Reserva:
    properties:
        fecha_entrada:
            - NotBlank: ~
            - Type: \DateTime
        fecha_salida:
            - NotBlank: ~
            - Type: \DateTime

proyecto\HotelBundle\Entity\Cliente:
    properties:
        nombre:
            - NotBlank: { message: "El nombre no puede estar vacío." }
            - Length:
                min: 2
                max: 50
                minMessage: "El nombre debería ser algo más largo."
                maxMessage: "Por favor, introduce tu nombre correcto."
        primerApellido:
            - NotBlank: { message: "El primer apellido no puede estar vacío." }
            - Length:
                min: 2
                max: 50
                minMessage: "El primer apellido debería ser algo más largo."
                maxMessage: "Por favor, introduce tu primer apellido correcto."
        segundoApellido:
            - Length:
                min: 2
                max: 50
                minMessage: "El segundo apellido debería ser algo más largo."
                maxMessage: "Por favor, introduce tu segundo apellido correcto."
        direccion:
            - NotBlank:  { message: "La dirección no puede estar vacía." }
            - Length:
                min: 10
                max: 50
                minMessage: "Por favor, introduce una dirección correcta."
                maxMessage: "Por favor, introduce una dirección correcta."
        ciudad:
            - NotBlank:  { message: "La ciudad no puede estar vacía." }
            - Length:
                min: 2
                max: 30
                minMessage: "Por favor, introduce una ciudad correcta."
                maxMessage: "Por favor, introduce una ciudad correcta."
        provincia:
            - NotBlank:  { message: "La provincia no puede estar vacía." }
            - Length:
                min: 2
                max: 30
                minMessage: "Por favor, introduce una provincia correcta."
                maxMessage: "Por favor, introduce una provincia correcta."
        cod_postal:
            - NotBlank:  { message: "El código postal no puede estar vacío." }
            - Length:
                min: 5
                max: 5
                exactMessage: "El código postal debe tener {{ limit }} caracteres."
        telefono:
            - NotBlank:  { message: "El teléfono no puede estar vacío." }
            - Length:
                min: 9
                max: 9
                exactMessage: "El teléfono debe tener {{ limit }} caracteres."
        email:
            - NotBlank:  { message: "El email no puede estar vacío." }
            - Email:
                message: Introduce un email correcto.
                checkMX: true
                checkHost: true