parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: hotel
    database_user: root
    database_password: null
    mailer_transport: gmail
#    mailer_mode: login
#    mailer_host: smtp.gmail.com
    mailer_host: ~
    mailer_user: symfony2hotel@gmail.com
    mailer_password: proyectohotel1234
    locale: es
    secret: d82db3e4b8b75db8263b4cdce8405f73905c6084
    database_path: null